name: OS 무관 미니콘다 설치 스크립트 테스트

on: [push, pull_request]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable and Run
        working-directory: "./1(2)-CS_basics" # 폴더 안으로 먼저 진입
        run: |
          chmod +x "./script.sh"
          "./script.sh" # 명령어에 괄호가 없으므로 안전

  test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script on Windows Git Bash
        shell: bash
        working-directory: "./1(2)-CS_basics" # 윈도우 시스템 레벨에서 안전하게 폴더 진입
        run: |
          "./script.sh" # 경로를 다 지웠기 때문에 Bash가 괄호 함수로 오해할 일이 절대 없음